-- Modelo relacional em 3FN (Oracle Database XE, PDB XEPDB1).
-- Identificadores sem aspas: Oracle normaliza para MAIÚSCULAS no dicionário de dados (boa prática usual).
-- Executado na primeira inicialização do container (gvenzl/oracle-xe).
-- Se já existir volume antigo com DDL anterior: docker compose down -v e subir de novo.

ALTER SESSION SET CONTAINER = XEPDB1;

CREATE TABLE etl.tipo_vinculo (
    id     NUMBER(5) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR2(32) NOT NULL,
    CONSTRAINT uq_tipo_vinculo_codigo UNIQUE (codigo)
);

CREATE TABLE etl.status_servidor (
    id     NUMBER(5) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR2(32) NOT NULL,
    CONSTRAINT uq_status_servidor_codigo UNIQUE (codigo)
);

CREATE TABLE etl.tipo_evento (
    id     NUMBER(5) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR2(32) NOT NULL,
    CONSTRAINT uq_tipo_evento_codigo UNIQUE (codigo)
);

INSERT INTO etl.tipo_vinculo (codigo) VALUES ('efetivo');
INSERT INTO etl.tipo_vinculo (codigo) VALUES ('comissionado');
INSERT INTO etl.tipo_vinculo (codigo) VALUES ('cedido');

INSERT INTO etl.status_servidor (codigo) VALUES ('ativo');
INSERT INTO etl.status_servidor (codigo) VALUES ('afastado');
INSERT INTO etl.status_servidor (codigo) VALUES ('exonerado');

INSERT INTO etl.tipo_evento (codigo) VALUES ('admissao');
INSERT INTO etl.tipo_evento (codigo) VALUES ('afastamento');
INSERT INTO etl.tipo_evento (codigo) VALUES ('desligamento');

COMMIT;

CREATE TABLE etl.orgao (
    id    NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sigla VARCHAR2(64) NOT NULL,
    CONSTRAINT uq_orgao_sigla UNIQUE (sigla)
);

CREATE TABLE etl.cargo (
    id   NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(256) NOT NULL,
    CONSTRAINT uq_cargo_nome UNIQUE (nome)
);

CREATE TABLE etl.pessoa (
    id              NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cpf             CHAR(11) NOT NULL,
    nome            VARCHAR2(512) NOT NULL,
    data_nascimento DATE,
    sexo            VARCHAR2(20),
    estado_civil    VARCHAR2(64),
    cor_raca        VARCHAR2(32),
    nacionalidade   VARCHAR2(64),
    email           VARCHAR2(256),
    telefone        VARCHAR2(64),
    CONSTRAINT uq_pessoa_cpf UNIQUE (cpf)
);

CREATE TABLE etl.vinculo (
    id                 NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pessoa_id          NUMBER(10) NOT NULL,
    orgao_id           NUMBER(10) NOT NULL,
    cargo_id           NUMBER(10) NOT NULL,
    tipo_vinculo_id    NUMBER(5) NOT NULL,
    status_servidor_id NUMBER(5) NOT NULL,
    matricula          VARCHAR2(128),
    salario_base       NUMBER(14, 2),
    lotacao            VARCHAR2(4000),
    data_admissao      DATE,
    data_saida         DATE,
    CONSTRAINT fk_vinculo_pessoa FOREIGN KEY (pessoa_id) REFERENCES etl.pessoa (id) ON DELETE CASCADE,
    CONSTRAINT fk_vinculo_orgao FOREIGN KEY (orgao_id) REFERENCES etl.orgao (id),
    CONSTRAINT fk_vinculo_cargo FOREIGN KEY (cargo_id) REFERENCES etl.cargo (id),
    CONSTRAINT fk_vinculo_tipo FOREIGN KEY (tipo_vinculo_id) REFERENCES etl.tipo_vinculo (id),
    CONSTRAINT fk_vinculo_status FOREIGN KEY (status_servidor_id) REFERENCES etl.status_servidor (id),
    CONSTRAINT uq_vinculo_um_por_pessoa UNIQUE (pessoa_id)
);

CREATE INDEX idx_vinculo_pessoa ON etl.vinculo (pessoa_id);
CREATE INDEX idx_vinculo_orgao ON etl.vinculo (orgao_id);

CREATE TABLE etl.evento (
    id                    NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pessoa_id             NUMBER(10) NOT NULL,
    id_evento_origem      VARCHAR2(128) NOT NULL,
    tipo_evento_id        NUMBER(5) NOT NULL,
    data_evento           DATE NOT NULL,
    codigo_categoria      VARCHAR2(32),
    indicador_retificacao VARCHAR2(32),
    numero_recibo         VARCHAR2(128),
    CONSTRAINT fk_evento_pessoa FOREIGN KEY (pessoa_id) REFERENCES etl.pessoa (id) ON DELETE CASCADE,
    CONSTRAINT fk_evento_tipo FOREIGN KEY (tipo_evento_id) REFERENCES etl.tipo_evento (id),
    CONSTRAINT uq_evento_origem UNIQUE (id_evento_origem)
);

CREATE INDEX idx_evento_pessoa ON etl.evento (pessoa_id);
CREATE INDEX idx_evento_data ON etl.evento (data_evento);

CREATE TABLE etl.avaliacao_desempenho (
    id              NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pessoa_id       NUMBER(10) NOT NULL,
    ciclo_avaliacao VARCHAR2(16) NOT NULL,
    nota            NUMBER(4, 1),
    CONSTRAINT fk_avaliacao_pessoa FOREIGN KEY (pessoa_id) REFERENCES etl.pessoa (id) ON DELETE CASCADE,
    CONSTRAINT uq_avaliacao_pessoa_ciclo UNIQUE (pessoa_id, ciclo_avaliacao)
);

COMMENT ON TABLE etl.pessoa IS 'Cadastro de pessoa física (identificação e contato).';
COMMENT ON TABLE etl.vinculo IS 'Vínculo empregatício com órgão e cargo.';
COMMENT ON TABLE etl.evento IS 'Eventos de folha/eSocial associados à pessoa.';
COMMENT ON TABLE etl.cargo IS 'Catálogo de cargos.';
COMMENT ON TABLE etl.orgao IS 'Catálogo de órgãos (executivo estadual).';

COMMIT;
